# Quantum Simulator

In [23]:
import numpy as np

## Gates and InputVector

In [24]:
def Qubit1(val):
    A = np.zeros(2)
    A[val] = 1
    return A

def basis(string):
    input_states = []
    
    for char in string:
        if char == '0':
            input_states.append(Qubit1(0))
        elif char == '1':
            input_states.append(Qubit1(1))
        elif char == '+':
            input_states.append((Qubit1(0) + Qubit1(1)) / np.sqrt(2))
        elif char == '-':
            input_states.append((Qubit1(0) - Qubit1(1)) / np.sqrt(2))

    result = input_states[0]
    for state in input_states[1:]:
        result = np.kron(result, state)
        
    return result

In [50]:
X_mat = np.array([[0, 1], [1, 0]])
Y_mat = np.array([[0, -1j], [1j, 0]])
Z_mat = np.array([[1, 0], [0, -1]])
H_mat = 1 / np.sqrt(2) * np.array([[1, 1], [1, -1]])
T_mat = np.array([[1, 0], [0, np.exp(1j * np.pi / 4)]])


def xgate(dim):
    step = X_mat
    for _ in range(dim - 1):
        step = np.kron(step, X_mat)
    return step


def ygate(dim):
    step = Y_mat
    for _ in range(dim - 1):
        step = np.kron(step, Y_mat)
    return step


def zgate(dim):
    step = Z_mat
    for _ in range(dim - 1):
        step = np.kron(step, Z_mat)
    return step


def Hgate(dim):
    step = H_mat
    for _ in range(dim - 1):
        step = np.kron(step, H_mat)
    return step


def Tgate(dim):
    step = T_mat
    for _ in range(dim - 1):
        step = np.kron(step, T_mat)
    return step


def CNOTGate(n_qubits, control, target):
    """
    Constructs an n-qubit CNOT matrix with specified control and target qubit indices.
    Indices are 0-based from left to right.
    """
    P0 = np.array([[1, 0], [0, 0]])
    P1 = np.array([[0, 0], [0, 1]])
    I  = np.eye(2)
    X  = np.array([[0, 1], [1, 0]])

    # Term 1: Control is |0> -> apply Identity to target
    term0 = [P0 if i == control else I for i in range(n_qubits)]
    
    # Term 2: Control is |1> -> apply X to target
    term1 = [X if i == target else (P1 if i == control else I) for i in range(n_qubits)]

    # Compute tensor products
    op0 = term0[0]
    op1 = term1[0]
    for gate0, gate1 in zip(term0[1:], term1[1:]):
        op0 = np.kron(op0, gate0)
        op1 = np.kron(op1, gate1)

    return op0 + op1

def CZGate(n_qubits, control, target):
    """
    Constructs an n-qubit CNOT matrix with specified control and target qubit indices.
    Indices are 0-based from left to right.
    """
    P0 = np.array([[1, 0], [0, 0]])
    P1 = np.array([[0, 0], [0, 1]])
    I  = np.eye(2)
    Z  = zgate(1)

    # Term 1: Control is |0> -> apply Identity to target
    term0 = [P0 if i == control else I for i in range(n_qubits)]
    
    # Term 2: Control is |1> -> apply X to target
    term1 = [Z if i == target else (P1 if i == control else I) for i in range(n_qubits)]

    # Compute tensor products
    op0 = term0[0]
    op1 = term1[0]
    for gate0, gate1 in zip(term0[1:], term1[1:]):
        op0 = np.kron(op0, gate0)
        op1 = np.kron(op1, gate1)

    return op0 + op1

check3 = CZGate(2, 0, 1)
check3

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0., -1.]])

In [43]:
xcheck0 = xgate(1) @ basis('0')
xcheck1 = xgate(1) @ basis('1')

ycheck0 = ygate(1) @ basis('0')
ycheck1 = ygate(1) @ basis('1')

zcheck0 = zgate(1) @ basis('0')
zcheck1 = zgate(1) @ basis('1')

Hcheck0 = Hgate(1) @ basis('0')
Hcheck1 = Hgate(1) @ basis('1')

Tcheck0 = Tgate(1) @ basis('0')
Tcheck1 = Tgate(1) @ basis('1')

Cnotcheck0 = CNOTGate(2, 0, 1) @ basis('10')
Cnotcheck1 = CNOTGate(2, 0, 1) @ basis('11')

display(xcheck0, xcheck1)
display(ycheck0, ycheck1)
display(zcheck0, zcheck1)
display(Hcheck0, Hcheck1)
display(Tcheck0, Tcheck1)
display(Cnotcheck0, Cnotcheck1)

array([0., 1.])

array([1., 0.])

array([0.+0.j, 0.+1.j])

array([0.-1.j, 0.+0.j])

array([1., 0.])

array([ 0., -1.])

array([0.70710678, 0.70710678])

array([ 0.70710678, -0.70710678])

array([1.+0.j, 0.+0.j])

array([0.        +0.j        , 0.70710678+0.70710678j])

array([0., 0., 0., 1.])

array([0., 0., 1., 0.])

In [38]:
Hgate(2) @ basis('+1')

array([ 0.70710678, -0.70710678,  0.        ,  0.        ])